name: Final test with real usage

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
      image: postgres:14
      env:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres

      litecord:
        image: ghcr.io/wumpyproject/litecord-docker-service
        env:
          LITECORD_HOSTNAME: litecord

          ADMIN_TOKEN: ADMIN_TOKEN

          POSTGRES_HOST: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
          
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Install dependencies
        run: pip install httpx

      - name: Run testing script
        run: python main.py
