name: Testing

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      testing:
        image: ghcr.io/bluenix2/service-container-registry-test

    steps:
      - name: Read environment variables
        env:
          TEST: abc
        run: |
          echo "$TEST"
